[package]
name = "cedille2-core"
version = "0.1.0"
edition = "2021"
authors = ["Andrew Marmaduke <marmaduke.andrew@gmail.com>"]

[dependencies]

internment = "=0.7.4"
ahash = "=0.8.6"
log ="0.4.14"
if_chain = "=1.0.2"
stacker = "=0.1.14"
imbl = "2.0.3"
colored = "=2"
